### ISSUE TITLE
incorrect names for network "castable" devices

### ISSUE THREAD

**Issue by mknoell** [GPMDP/electron-chromecast#17]
As requested, I am re-posting this issue here. Thanks for a fantastic product BTW!

The original now closed post is located at:
https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1523#event-765990058

---

**OS:** 
Windows 10 (v1607)

 **Issue Descriptions:**
List of "castable" devices is wrong. Here is a listing of the devices on my network (as seen by the chrome browse I am using to write this):

![2016-08-24 06_52_45-groove music](https://cloud.githubusercontent.com/assets/21219017/17929697/c43bddfe-69c7-11e6-94fb-93a5bc375de2.png)

However, in the app, when I attempt to cast - this is what appears:

![2016-08-24 06_43_58-start](https://cloud.githubusercontent.com/assets/21219017/17929679/a39be382-69c7-11e6-8e17-ba67d7e64427.png)

First it appears that the "." in the name of the device is causing the device name to truncate. In addition there is an incorrect number of devices listed - no idea were that's coming from. Interestingly, when select the correct "a" from the list, casting works.

**Steps to Reproduce:** 
Every time I go to cast it shows up. Maybe it's my naming convention (which differentiates video from audio casting devices) but this is the only place I have seen this naming disconnect.

**Comment by MarshallOfSound** [comment]
Probably fixed in f4185d47d96074540e73e51065734843a4c08ae5
