### ISSUE TITLE
Chromecast API v3 Support

### ISSUE THREAD

**Issue by Guichaguri** [GPMDP/electron-chromecast#40]
Does this implementation supports Chromecast API v3? If not, are there plans to support it?

**Comment by MarshallOfSound** [comment]
I wasn't even aware `v3` had been released.  However due to the massive amount of work required to get `v2` working I'm going to say we probably won't be actively aiming for `v3`.

> Version note: While sender apps written for Cast SDK v2 will continue to work with Cast SDK v3, we recommend upgrading those apps to v3 for higher reliability and easier maintenance.

TLDR: Maybe, probably not, don't really need to anyway 👍

**Comment by Guichaguri** [comment]
You're right. The problem is that Google is going to remove `v2` docs sometime, and it might be harder for someone trying to start/maintain a project that supports chromecast.

There aren't that many changes in `v3`, I might send a PR to support both `v2` and `v3` at the same time
