### ISSUE TITLE
Use yarn.lock?

### ISSUE THREAD

**Issue by jostrander** [GPMDP/electron-chromecast#44]
I've just started using yarn and noticed there is no yarn.lock here. Should we consider using it?

**Comment by MarshallOfSound** [comment]
I tend to avoid yarn lock files in version control at the moment as the cross platform story doesn't quite work very well.  This makes electron deps + yarn a very difficult thing to make work correctly.

**Comment by jostrander** [comment]
Fair enough, will close for now.
