### ISSUE TITLE
Receiver List Empty

### ISSUE THREAD

**Issue by kee23** [GPMDP/electron-chromecast#52]
I'm trying to recreate the [CastHelloText-chrome](https://github.com/googlecast/CastHelloText-chrome) functionality within an Electron app, however, it is not detecting any Chromecast receivers.

I've tried running the CastHelloText-chrome sample on a Chrome browser and it is able to find receivers. But in Electron, I've tried using the default app id given in the sample (794B7BBF) and chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID, but it's still not finding anything.

Trying to use it, I get `onError: {"code":"RECEIVER_UNAVAILABLE","description":null,"details":{}}`.

Is there anything special regarding ports or networking that I am missing? If there is a sample app using electron-chromcast, that would be appreciated as well.

**Comment by inderpreetsingh** [comment]
Hmm, Interesting! 🤔  I would need to see your code to be of any use in figuring out that error, however on your request for a sample app, how about this? 
https://github.com/ammumaddy/music-for-pc 

I hope it helps 👍

**Comment by MarshallOfSound** [comment]
@inderpreetsingh Is that repo really a direct copy of GPMDP but renamed and not forked....  That's not cool dude 😕 

@kee23 Check out the official code here https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

**Comment by inderpreetsingh** [comment]
@MarshallOfSound, Hey this repo belongs to https://github.com/ammumaddy, you might want to contact him about the forking. I have nothing to do with it :laughing: I just found it via github code search. 

My profile is https://github.com/inderpreetsingh.
