### ISSUE TITLE
Support for Google Cast groups

### ISSUE THREAD

**Issue by MarshallOfSound** [GPMDP/electron-chromecast#8]
As per MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/1292

It was revealed that Google Cast groups are advertised on a different service name to individual cast services.

They are advertised on `googlezone`, we should look into how we support these.

/cc @jostrander

**Comment by jostrander** [comment]
There's no other relevant information in the googlezone result though is there?

**Comment by MarshallOfSound** [comment]
Idk, I don't have a cast group setup.

The results in that issue though are the results from a wildcard mdns scan so they are missing a lots of details.

**Comment by charles222a203** [comment]
Has there been any progress on this? The app lists my CC audio group, just can't cast to it; it sends the audio to a single speaker that's part of the group.

**Comment by nachogo** [comment]
First a  big thanks to GPMDP developer. I use it a lot. I also have the google cast audio group problem. I can see in the GPMDP the name of the group, the one I have in my setup (a chromecast audio+a Sony gcast enable speaker) but, when selected, the audio is sent only to the chromecast audio. No problem sending just to sony speaker or CC audio. I hope the problem will be sort out in the near future. Thanks again to the development work.

**Comment by jostrander** [comment]
As it stands neither @MarshallOfSound or I have cast groups to test with, so unfortunately were stuck relying on someone who has them to contribute a fix, or provide information that would be useful for debugging.

**Comment by nachogo** [comment]
Thanks for your quick reply. Unfortunatly I am not a programer, I´m a musician, so i´m afraid  I can´t help or be useful in debugging the problem. Anyway, thanks again for your amazing in progress work with GPMDP. I, of course, will keep using it. Much better than a chrome tab. No doubt.

**Comment by paolee** [comment]
I love the player and I really would love to have the possibility of group playing. I'm not a programmer, so I cannot help, just wanted to show my interest in that feature :) Thanks for this great work

**Comment by bonavox007** [comment]
I got the same problem. Got three Chromecast Audio in a group, but GPMDP only cast to one of them. Casting to the group from Chrome & iOS work flawlessly.

Soon Onkyo comes with a firmware to support GC, and and I see more and more AVR's and standalone speakers are supporting GC. So I suspect grouping will be more common :)  GPM & GC have become way better than iTunes, AirPlay, Spotify and Spotify Connect, and after invested in cheap hardware and a subscription Google effectively replaced both Apple and Spotify in my home. Not bad.

**Comment by HolstenerLiesel** [comment]
Same problem here, maybe you can provide some info as to what kind of debug information you need and how to get the logs? I'd be willing to give it a shot.

**Comment by brendanheyu** [comment]
Love your work Devs - I use this on every machine I own, and suggest it to all my fellow google music addicts. :)

This bug: When I cast to my "Whole house" group (3x Chromecast Audio + 1x Google Home) it seems to connect only to one Chromecast ("Man Cave Chromecast A") - audio only emits from that Chromecast. However - all the other Chromecasts in the group seem to stop what they are doing (go silent), but don't emit any music...

I'm using GPMDP 4.2.0 on Windows 10.

I'm happy to list all device names and firmware versions of the Chromecasts if that will help.

**Comment by jostrander** [comment]
Can anyone of you provide an mDNS scan of your network with the chromecast groups online and available? You can use [this Chrome Extension](https://chrome.google.com/webstore/detail/mdns-browser/kipighjpklofchgbdgclfaoccdlghidp).

**Comment by jostrander** [comment]
Alternatively, if you are on mac or windows with Bonjour installed you can use `dns-sd -Z _googlecast._tcp` to scan, it shows more data that might help with researching this.

**Comment by charles222a203** [comment]
Here's a screenshot of the Terminal command.

![screen shot 2017-03-18 at 12 02 32 pm](https://cloud.githubusercontent.com/assets/23641297/24073747/d0231620-0bd2-11e7-87ac-44d7e60b95de.png)

**Comment by MarshallOfSound** [comment]
@charles222a203 Thanks for the data set, can you also run `dns-sd -Z _googlezone._tcp`

**Comment by charles222a203** [comment]
Well, I do have coffee I need to drink, but sure :p

**Comment by charles222a203** [comment]
![screen shot 2017-03-18 at 12 08 08 pm](https://cloud.githubusercontent.com/assets/23641297/24073794/a531de00-0bd3-11e7-9cb8-a168e4274790.png)

**Comment by jostrander** [comment]
Just for clarification, how many groups do you have setup?

**Comment by charles222a203** [comment]
Just one.

**Comment by MarshallOfSound** [comment]
@charles222a203 Consisting of which casts?

**Comment by charles222a203** [comment]
All the Chromecasts Audio. The Homes, Shield, and the Ultra aren't part of a group.

**Comment by jostrander** [comment]
So your living room device in this case appears to be the master. Can you navigate to:

http://7dd3a0c3-baf4-2175-c7bd-980a4f9cbb75.local:8008/setup/eureka_info?options=detail

and see if there is anything related to audio groups in there. There is some private data in there such as mac address and wireless bssid's, feel free to sensor that info, but can you post the result?

**Comment by jostrander** [comment]
Also notice @MarshallOfSound that the Home group operates on port 42800 and not 8009, could that be our issue?

**Comment by charles222a203** [comment]
```
{"bssid":"90:72:40:10:dc:db","build_version":"78337","cast_build_revision":"1.22.78337","closed_caption":{},"connected":true,"detail":{"icon_list":[{"depth":32,"height":55,"mimetype":"image/png","url":"/setup/icon.png","width":98}],"locale":{"display_string":"English (United States)"},"manufacturer":"Google Inc.","model_name":"Chromecast Audio","timezone":{"display_string":"Eastern Daylight Time (New York)","offset":-240}},"ethernet_connected":false,"has_update":false,"hotspot_bssid":"FA:8F:CA:96:D1:CD","ip_address":"10.0.0.165","locale":"en-US","location":{"country_code":"US","latitude":255.0,"longitude":255.0},,"name":"Living Room audio","noise_level":-88,"opencast_pin_code":"1021","opt_in":{"crash":true,"location":false,"opencast":true,"stats":true},"public_key":"MIIBCgKCAQEAvlgyJ7hDsJ35XIOyGJUJfTbCve/wCPnSUUudBWjFlSR2gfO7mZgoH8VF8gnsIvqQxIYNOU2xGZzlHX+VDccELj4+oJsY1PM59KZ0aNXjSkr7eMVukUuek3bcO+YPjfeeKEqdFFctkBj2vGXxg02Emlhbp74qUZA5ppEHThhsAL5RmU1/LNngwlASy7DJFH6wQSb8iRcpVMU6Sbdpl6Wkd8K4kQrrUZB3aBO9P0Yz9aPjoWdP/grjZEG3DJk3/56oPNAuCz00NQjq3SST7+Wfu+geCoqbehuU6rY2WFoecnEnrz/Zwxl0h7qfKfgjKosuqFoq4EhY4Egu0vRX43/pKwIDAQAB","release_track":"stable-channel","setup_state":60,"setup_stats":{"historically_succeeded":true,"num_check_connectivity":0,"num_connect_wifi":0,"num_connected_wifi_not_saved":0,"num_initial_eureka_info":0,"num_obtain_ip":0},"signal_level":-37,"ssdp_udn":"7dd3a0c3-baf4-2175-c7bd-980a4f9cbb75","time_format":1,"timezone":"America/New_York","tos_accepted":true,"uma_client_id":"704429C2-0B30-4FC1-9202-7C1B2A0A2DE4","uptime":35429.52,"version":7,"wpa_configured":true,"wpa_id":0,"wpa_state":10}
```

This was the result @jostrander. Doesn't look like there's anything related to groups in there, though.

**Comment by jostrander** [comment]
https://github.com/thibauts/node-castv2/blob/master/lib/client.js#L28

https://github.com/GPMDP/electron-chromecast/blob/master/src/cast/_Classes/Session.js#L12

If we change this to an object with the port number, we could push a test version that someone could potentially check.

**Comment by charles222a203** [comment]
sure, I'll beta for you. Might be later today, though.

**Comment by jostrander** [comment]
Just pushed a change up, you will need to have a development version of GPMDP and use this commit cbddb5d697c2ebd795511e09cfe554c0a7df4af3 instead of the npm version of `electron-chromecast`.

**Comment by charles222a203** [comment]
I'm not sure about how to get a dev version and use the commit?

**Comment by jostrander** [comment]
Check out the development FAQ if you are interested in setting up a development environment, from there you'll need to change package.json to use the git hash for electron-chromecast, then install, rebuild, and start.

**Comment by tyates** [comment]
Ran into this issue after getting some Google Homes and setting them up in an audio group. Can I help at all? I'm an Android developer so not exactly familiar with Electron but at least _somewhat_ technically competent. I'll see if I can get the dev environment set up.

**Comment by jostrander** [comment]
Has anyone had the chance to test this out? I'm pretty sure this is the way to resolve this but I don't have any audio devices to test with.

**Comment by Smashman** [comment]
I have an audio group and would be happy to work with you guys to fix the issue.

**Comment by braytonstafford** [comment]
```
git clone https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-.git gpmdp
cd gpmdp
```
Changed this line in package.json 
From:
> "electron-chromecast": "^1.0.17",

To:
> "electron-chromecast": "https://github.com/GPMDP/electron-chromecast.git#cbddb5d",

Then ran these to install dependencies, build, and start
```
npm install
npm run build
npm start
```
After it started I do not have the chromecast icon in the bottom right corner to try and cast.  I verified chromecast-electron is in the node-modules/ directory and when i look at its package.json i can see that it did pull from the commit.  Willing to do more troubleshooting and thank you for what you do.
```
MacBook:electron-chromecast$ cat package.json
{
  "_from": "git+https://github.com/GPMDP/electron-chromecast.git#cbddb5d",
```

Some info when i ran npm start:
```
$ npm start

> google-play-music-desktop-player@4.4.0 prestart /Users/braytonstafford/Projects/gpmdp
> pre-flight && node vendor/patch_dev.js && electron-rebuild --types=prod,optional

Starting pre-flight checks
Processing production dependencies
Processing development dependencies
Processing optional dependencies
Dependencies are all up to date, looking good!
Monkey patching your Info.plist
✔ Rebuild Complete

> google-play-music-desktop-player@4.4.0 start /Users/braytonstafford/Projects/gpmdp
> electron . --dev

info: Application started.
error: Last.fm API keys have not been set!
debug: Renderer process logger initialized.
```

[Screeshot](http://i.imgur.com/C8aVh4W.png) of the UI after npm start

Side Notes:
I only have one cast group with 3 device in it. One google home and 2 chromecast audios.
Now using node v6.2.2 (npm v3.9.5)
[Development FAQ](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/wiki/Development-FAQ)


My `dns-sd -Z _googlecast._tcp`
```
Browsing for _googlecast._tcp
DATE: ---Thu 10 Aug 2017---
 9:41:17.187  ...STARTING...

; To direct clients to browse a different domain, substitute that domain in place of '@'
lb._dns-sd._udp                                 PTR     @

; In the list of services below, the SRV records will typically reference dot-local Multicast DNS names.
; When transferring this zone file data to your unicast DNS server, you'll need to replace those dot-local
; names with the correct fully-qualified (unicast) domain name of the target host offering the service.

_googlecast._tcp                                PTR     Google-Home-574eb559e8a51a2a7e0baadbad602821._googlecast._tcp
Google-Home-574eb559e8a51a2a7e0baadbad602821._googlecast._tcp SRV     0 0 8009 574eb559-e8a5-1a2a-7e0b-aadbad602821.local. ; Replace with unicast FQDN of target host
Google-Home-574eb559e8a51a2a7e0baadbad602821._googlecast._tcp TXT     "id=574eb559e8a51a2a7e0baadbad602821" "cd=860AD2FE10A0AF558B487AF64F0D0780" "rm=54E05FA7104CD0CE" "ve=05" "md=Google Home" "ic=/setup/icon.png" "fn=Living room Home" "ca=2052" "st=1" "bs=FA8FCA8260BD" "nf=1" "rs=Google Play Music"

_googlecast._tcp                                PTR     Chromecast-Audio-143bb301c914a05d89984df0873c8272._googlecast._tcp
Chromecast-Audio-143bb301c914a05d89984df0873c8272._googlecast._tcp SRV     0 0 8009 143bb301-c914-a05d-8998-4df0873c8272.local. ; Replace with unicast FQDN of target host
Chromecast-Audio-143bb301c914a05d89984df0873c8272._googlecast._tcp TXT     "id=143bb301c914a05d89984df0873c8272" "cd=2453787CECCE14766671E21C693E4A15" "rm=125AF306B2A8BE86" "ve=05" "md=Chromecast Audio" "ic=/setup/icon.png" "fn=Office Speakers" "ca=2052" "st=0" "bs=FA8FCA9112F7" "nf=1" "rs="

_googlecast._tcp                                PTR     Chromecast-Audio-2525945dc4ad7e66ff16e790ca11e036._googlecast._tcp
Chromecast-Audio-2525945dc4ad7e66ff16e790ca11e036._googlecast._tcp SRV     0 0 8009 2525945d-c4ad-7e66-ff16-e790ca11e036.local. ; Replace with unicast FQDN of target host
Chromecast-Audio-2525945dc4ad7e66ff16e790ca11e036._googlecast._tcp TXT     "id=2525945dc4ad7e66ff16e790ca11e036" "cd=C6B782455FAF178DFD87C6B3C53F0B56" "rm=6F58937869843825" "ve=05" "md=Chromecast Audio" "ic=/setup/icon.png" "fn=Bedroom Speakers" "ca=2052" "st=0" "bs=FA8FCA910A07" "nf=1" "rs="

_googlecast._tcp                                PTR     Google-Cast-Group-d208a0994ae94b54ba53de19aa875891-1._googlecast._tcp
Google-Cast-Group-d208a0994ae94b54ba53de19aa875891-1._googlecast._tcp SRV     0 0 42948 143bb301-c914-a05d-8998-4df0873c8272.local. ; Replace with unicast FQDN of target host
Google-Cast-Group-d208a0994ae94b54ba53de19aa875891-1._googlecast._tcp TXT     "id=d208a099-4ae9-4b54-ba53-de19aa875891" "cd=d208a099-4ae9-4b54-ba53-de19aa875891" "rm=125AF306B2A8BE86" "ve=05" "md=Google Cast Group" "ic=/setup/icon.png" "fn=All Speakers" "ca=2084" "st=0" "bs=FA8FCA9112F7" "nf=1" "rs="
```

My `dns-sd -Z _googlezone._tcp`
```
Browsing for _googlezone._tcp
DATE: ---Thu 10 Aug 2017---
 9:39:00.597  ...STARTING...

; To direct clients to browse a different domain, substitute that domain in place of '@'
lb._dns-sd._udp                                 PTR     @

; In the list of services below, the SRV records will typically reference dot-local Multicast DNS names.
; When transferring this zone file data to your unicast DNS server, you'll need to replace those dot-local
; names with the correct fully-qualified (unicast) domain name of the target host offering the service.

_googlezone._tcp                                PTR     574eb559-e8a5-1a2a-7e0b-aadbad602821._googlezone._tcp
574eb559-e8a5-1a2a-7e0b-aadbad602821._googlezone._tcp SRV     0 0 10001 574eb559-e8a5-1a2a-7e0b-aadbad602821.local. ; Replace with unicast FQDN of target host
574eb559-e8a5-1a2a-7e0b-aadbad602821._googlezone._tcp TXT     "id=574eb559-e8a5-1a2a-7e0b-aadbad602821" "d208a099-4ae9-4b54-ba53-de19aa875891=0|All Speakers" "574eb559-e8a5-1a2a-7e0b-aadbad602821=7|Living room Home"

_googlezone._tcp                                PTR     143bb301-c914-a05d-8998-4df0873c8272._googlezone._tcp
143bb301-c914-a05d-8998-4df0873c8272._googlezone._tcp SRV     0 0 10001 143bb301-c914-a05d-8998-4df0873c8272.local. ; Replace with unicast FQDN of target host
143bb301-c914-a05d-8998-4df0873c8272._googlezone._tcp TXT     "id=143bb301-c914-a05d-8998-4df0873c8272" "d208a099-4ae9-4b54-ba53-de19aa875891=1|All Speakers"

_googlezone._tcp                                PTR     2525945d-c4ad-7e66-ff16-e790ca11e036._googlezone._tcp
2525945d-c4ad-7e66-ff16-e790ca11e036._googlezone._tcp SRV     0 0 10001 2525945d-c4ad-7e66-ff16-e790ca11e036.local. ; Replace with unicast FQDN of target host
2525945d-c4ad-7e66-ff16-e790ca11e036._googlezone._tcp TXT     "id=2525945d-c4ad-7e66-ff16-e790ca11e036" "d208a099-4ae9-4b54-ba53-de19aa875891=0|All Speakers"

**Comment by Menloman** [comment]
Just bringing this back up, looks like you guys were on a roll, any solution? 

Thanks in advance, great player would love to see group speakers working.

**Comment by braytonstafford** [comment]
I'm available to do more testing, just not sure how to get that cast icon to show up when running the test build.  I'll dig into it a little more but could use some direction.

**Comment by jostrander** [comment]
@braytonstafford What OS? You need bonjour installed on windows, or avahi dev libs on linux.

**Comment by braytonstafford** [comment]
MacOS 10.12.6 (16G29)

**Comment by SaintDude** [comment]
In the same boat as everyone here.  LOVE GPMDP, but attempts to cast to groups always result in a single audio device in the group receiving the audio.  And since I pretty much only use my laptop for home listening, where I always need to cast to multiple devices, GPMPD is rendered just about useless.  Which pains me.

If someone can confirm the cast icon issue has been resolved in the fix by @jostrander I'll set up a dev environment and give it a go.  I have a few audio groups including both ChromeCast Audios and Google Homes.

**Comment by Wehrdo** [comment]
I built GPMDP with the commit from @jostrander, and like @braytonstafford experienced, the cast button does not show up (I'm on Windows). When I switch back to the master branch of electron-chromecast, the cast button reappears.

What do you all use for debugging? I wasn't able to get VS Code to hit breakpoints in debug mode. I wanted to look closer at what was going on in electron-chromecast without having to pepper console.log statements everywhere. Here's the launch.json I'm using:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Main Process",
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "windows": {
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron.cmd"
      },
      "program": "${workspaceRoot}/build/index.js",
      "protocol": "legacy"
    }
  ]
}
```

**Comment by jostrander** [comment]
It looks like my branch may need to be rebased on top of the current master in order to work with the latest GPMDP, maybe give that a try?

**Comment by Wehrdo** [comment]
I actually tried that already (merged master into your branch), thinking there might be some fixes in master that were necessary. No luck, unfortunately.

**Comment by MarshallOfSound** [comment]
Coming in the next release 👍
